[package]

name = "uhub_proxy"
version = "0.0.1"
authors = [ "Hector Martin <marcan@marcan.st>" ]

[dependencies]

mio="0.5.0"
#openssl="0.7.8"
bytes = "0.3.0"
env_logger = "0.3.3"
getopts = "0.2"
log = "0.3.5"
net2 = "0.2.26"
time = "0.1.35"
